### PR TITLE
Updated build system for compatibility with new hypervisor build system

### PR DESCRIPTION
**Pull request by JaredWright**
This PR fixes compatibility between the extended apis and the new hypervisor build system. Travis CI for this PR will not pass until the new build system is merged onto hypervisor/dev.

### CODE REVIEW

**Comment by rianquinn** [comment]
What is the status of this?

**Comment by JaredWright** [comment]
Good question, I've been waiting until dev was merged. I'll push one small update to .travis.yml and see if CI is passing yet. It should be getting close.

**Comment by JaredWright** [comment]
It looks like this PR is going to depend on a small feature being added to the build system in the hypervisor repo. I need to add the ability to specify a path to the extended APIs from the main hypervisor repo. I had taken that feature out of the main hypervisor repo with the hopes of re-thinking how bareflank extensions will integrate with the main repo altogether. However, it looks like we'll need to re-introduce that feature for the time being.

**Comment by rianquinn** [comment]
Is this fix temporary?

**Comment by JaredWright** [comment]
This fix is somewhat temporary in the sense that it brings the extended apis into compatibitliy with the main hypervisor repo, but the mechanism for integrating the two repos together will likely be changed in the near future. Is that what you were asking?

**Comment by JaredWright** [comment]
Also, this PR still isn't ready for merging. If you'd like, you can close this PR until I can get a small feature merged onto hypervisor/dev that this PR depends on.

**Pull request closed without merging**
