### PR TITLE
xAPIC virtualization

### PR DESCRIPTION
**Pull request by connojd**

### CODE REVIEW

**Comment by connojd** [comment]
@JaredWright this is ready I think. I took heavy handed approach for the cygwin issue; there is likely a better way but would like some input

**Comment by JaredWright** [comment]
So the "Cygwin fix" is essentially saying that we do not support building the extended APIs from Windows at all.

Can you give me a summary of the issue you are having? If it seems reasonably small, I am willing to merge this PR as-is and then will volunteer to look into the build issue after its merged.

**Comment by connojd** [comment]
The issue is that CMake if adding '-rdynamic' to the linker flags, and the version of ld used by cygwin doesn't support that option apparently. I imagine it's possible to tell CMake not to do this, but I figured someone else with more CMake experience would have better judgement for that.

**Comment by rianquinn** [comment]
Have we tried:

```
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")
```

**Comment by JaredWright** [comment]
I don't believe that @connojd has a suitable Windows/Cygwin environment handy, so I'll merge this now start looking into the Cygwin issue right now.

Thanks again for re-organizing the commit history!

**Pull request merged**
